### PR TITLE
Issue 22

### LINKED ISSUE #22: setup continuous integration using travis

### PR DESCRIPTION
**Pull request by AntonioLangiu**
Now travis-ci works! 

Closes #22.

### CODE REVIEW

**Comment by bassosimone** [comment]
@AntonioLangiu however I see that travis-ci fails. Is it correct to say that this pull request depends on measurement-kit/measurement-kit#212 such that, until that pull request is merged, here travis-ci is going to fil?

**Comment by AntonioLangiu** [comment]
Now travis doesn't fail. It was beacause it downloaded the "master" branch of m-kit. Now it download the branch with the fixed issues and it compile. Maybe is better to merge the [fixes in this PR](https://github.com/measurement-kit/measurement-kit/pull/212) to avoid another change of branch in the Podfile!

**Comment by bassosimone** [comment]
Alright, when the branch is merged in measurement-kit, ping me and I'll follow up with this!

**Comment by lorenzoPrimi** [comment]
@AntonioLangiu can you check this and merge if needed?

**Comment by AntonioLangiu** [comment]
@lorenzoPrimi I will check this tomorrow. Actually the branch specified in the `Podfile` has been deleted, so we should use the default tag defined in the pod.

**Comment by lorenzoPrimi** [comment]
@AntonioLangiu could it be the branch I merged today into master?

**Comment by AntonioLangiu** [comment]
@lorenzoPrimi  Sorry for all this commits, but I had to figure out what is the problem on travis. I found out that the cocoapod version installed in the xcode-image must be updated, now it finds the pod and compiles it! 

The only problem now is this warning:
`WARNING: Using Objective-C testing without specifying a scheme and either a workspace or a project is deprecated.`

I think it's not important and we can live with it, but if we want to solve the problem, we should also build the xcode project in the travis script.
This can be done with:
`xcodebuild -workspace Libight_iOS.xcworkspace/ -scheme Libight_iOS build`
I tried it but I have some Code Sign errors. @lorenzoPrimi We are using your key and I think [this](https://github.com/travis-ci/travis-ci/issues/3072#issuecomment-68691059) can be a solution!

**Comment by lorenzoPrimi** [comment]
@AntonioLangiu don't think this is the optimal solution, I was using my personal dev cert to deploy the app on my device.
Every person should use its own dev cert (now apple allows to deploy apps without a paid account)

**Comment by AntonioLangiu** [comment]
Ok, now this PR is ok. We compile the cocoapod and the correct xcode scheme inside travis! 
@bassosimone can you check it?

**Comment by bassosimone** [comment]
Testing this pull request right now!

**Pull request merged**
