### PR TITLE
Project rename

### PR DESCRIPTION
**Pull request by lorenzoPrimi**

### CODE REVIEW

**Comment by bassosimone** [comment]
Thanks! Will merge as soon as travis-ci build completes!

**Comment by bassosimone** [comment]
@lorenzoPrimi, you should also fix the workspace name passed [to travis-ci to repair the build](https://travis-ci.org/measurement-kit/measurement-kit-app-ios/builds/123966109#L3471).

**Comment by bassosimone** [comment]
Thank you! We can now merge!

**Comment by anadahz** [comment]
Yey to the new project name!

**Pull request merged**
